schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        project_name:
          type: string
          description: "The project name for your VPC"
          default: "simple-vpc"
        vpc_cidr:
          type: string
          description: "This CIDR range for your VPC"
          default: 10.42.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|18|24))
        public_subnet_one_cidr:
          type: string
          description: "The CIDR range for public subnet"
          default: 10.42.0.0/17
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32))
        private_subnet_one_cidr:
          type: string
          description: "The CIDR range for private subnet"
          default: 10.42.128.0/17
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32))
